// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../state.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `anyhow_to_string`, `build_metadata_payload`, `build_tick_payload`, `get_state`, `is_subtitle_path`, `is_video_path`, `to_info_hash_hex`, `wait_until_torrent_updatable`

/// Initialize the torrent session and start the HTTP server
Future<int> initTorrentSession({required String cacheDir}) =>
    RustLib.instance.api.crateApiTorrentInitTorrentSession(cacheDir: cacheDir);

/// Start a torrent from a magnet URI
Future<TorrentMetadataPayload> startTorrent({required String magnetUri}) =>
    RustLib.instance.api.crateApiTorrentStartTorrent(magnetUri: magnetUri);

/// Start a torrent from .torrent file bytes
Future<TorrentMetadataPayload> startTorrentFile({
  required List<int> torrentBytes,
}) => RustLib.instance.api.crateApiTorrentStartTorrentFile(
  torrentBytes: torrentBytes,
);

/// Select a file to play and return the stream URL
Future<String> selectTorrentFile({
  required String infoHash,
  required BigInt fileIndex,
}) => RustLib.instance.api.crateApiTorrentSelectTorrentFile(
  infoHash: infoHash,
  fileIndex: fileIndex,
);

/// Pause a torrent
Future<void> pauseTorrent({required String infoHash}) =>
    RustLib.instance.api.crateApiTorrentPauseTorrent(infoHash: infoHash);

/// Resume a torrent
Future<void> resumeTorrent({required String infoHash}) =>
    RustLib.instance.api.crateApiTorrentResumeTorrent(infoHash: infoHash);

/// Stop and remove a torrent
Future<void> stopTorrent({required String infoHash}) =>
    RustLib.instance.api.crateApiTorrentStopTorrent(infoHash: infoHash);

/// Get the current tick stats for a torrent
Future<TorrentTickPayload?> getTorrentTick({required String infoHash}) =>
    RustLib.instance.api.crateApiTorrentGetTorrentTick(infoHash: infoHash);

/// Get the stream URL for a file (without selecting it)
Future<String> getStreamUrl({
  required String infoHash,
  required BigInt fileIndex,
}) => RustLib.instance.api.crateApiTorrentGetStreamUrl(
  infoHash: infoHash,
  fileIndex: fileIndex,
);
