// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/torrent.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1669389909;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutter_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiTorrentGetStreamUrl({
    required String infoHash,
    required BigInt fileIndex,
  });

  Future<TorrentTickPayload?> crateApiTorrentGetTorrentTick({
    required String infoHash,
  });

  Future<int> crateApiTorrentInitTorrentSession({required String cacheDir});

  Future<void> crateApiTorrentPauseTorrent({required String infoHash});

  Future<void> crateApiTorrentResumeTorrent({required String infoHash});

  Future<String> crateApiTorrentSelectTorrentFile({
    required String infoHash,
    required BigInt fileIndex,
  });

  Future<TorrentMetadataPayload> crateApiTorrentStartTorrent({
    required String magnetUri,
  });

  Future<TorrentMetadataPayload> crateApiTorrentStartTorrentFile({
    required List<int> torrentBytes,
  });

  Future<void> crateApiTorrentStopTorrent({required String infoHash});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiTorrentGetStreamUrl({
    required String infoHash,
    required BigInt fileIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          sse_encode_usize(fileIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorrentGetStreamUrlConstMeta,
        argValues: [infoHash, fileIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorrentGetStreamUrlConstMeta =>
      const TaskConstMeta(
        debugName: "get_stream_url",
        argNames: ["infoHash", "fileIndex"],
      );

  @override
  Future<TorrentTickPayload?> crateApiTorrentGetTorrentTick({
    required String infoHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_torrent_tick_payload,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorrentGetTorrentTickConstMeta,
        argValues: [infoHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorrentGetTorrentTickConstMeta =>
      const TaskConstMeta(
        debugName: "get_torrent_tick",
        argNames: ["infoHash"],
      );

  @override
  Future<int> crateApiTorrentInitTorrentSession({required String cacheDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cacheDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorrentInitTorrentSessionConstMeta,
        argValues: [cacheDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorrentInitTorrentSessionConstMeta =>
      const TaskConstMeta(
        debugName: "init_torrent_session",
        argNames: ["cacheDir"],
      );

  @override
  Future<void> crateApiTorrentPauseTorrent({required String infoHash}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorrentPauseTorrentConstMeta,
        argValues: [infoHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorrentPauseTorrentConstMeta =>
      const TaskConstMeta(debugName: "pause_torrent", argNames: ["infoHash"]);

  @override
  Future<void> crateApiTorrentResumeTorrent({required String infoHash}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorrentResumeTorrentConstMeta,
        argValues: [infoHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorrentResumeTorrentConstMeta =>
      const TaskConstMeta(debugName: "resume_torrent", argNames: ["infoHash"]);

  @override
  Future<String> crateApiTorrentSelectTorrentFile({
    required String infoHash,
    required BigInt fileIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          sse_encode_usize(fileIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorrentSelectTorrentFileConstMeta,
        argValues: [infoHash, fileIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorrentSelectTorrentFileConstMeta =>
      const TaskConstMeta(
        debugName: "select_torrent_file",
        argNames: ["infoHash", "fileIndex"],
      );

  @override
  Future<TorrentMetadataPayload> crateApiTorrentStartTorrent({
    required String magnetUri,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(magnetUri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_torrent_metadata_payload,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorrentStartTorrentConstMeta,
        argValues: [magnetUri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorrentStartTorrentConstMeta =>
      const TaskConstMeta(debugName: "start_torrent", argNames: ["magnetUri"]);

  @override
  Future<TorrentMetadataPayload> crateApiTorrentStartTorrentFile({
    required List<int> torrentBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(torrentBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_torrent_metadata_payload,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorrentStartTorrentFileConstMeta,
        argValues: [torrentBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorrentStartTorrentFileConstMeta =>
      const TaskConstMeta(
        debugName: "start_torrent_file",
        argNames: ["torrentBytes"],
      );

  @override
  Future<void> crateApiTorrentStopTorrent({required String infoHash}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorrentStopTorrentConstMeta,
        argValues: [infoHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorrentStopTorrentConstMeta =>
      const TaskConstMeta(debugName: "stop_torrent", argNames: ["infoHash"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  TorrentTickPayload dco_decode_box_autoadd_torrent_tick_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_torrent_tick_payload(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TorrentMetadataFilePayload>
  dco_decode_list_torrent_metadata_file_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_torrent_metadata_file_payload)
        .toList();
  }

  @protected
  TorrentTickPayload? dco_decode_opt_box_autoadd_torrent_tick_payload(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_torrent_tick_payload(raw);
  }

  @protected
  TorrentMetadataFilePayload dco_decode_torrent_metadata_file_payload(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TorrentMetadataFilePayload(
      index: dco_decode_usize(arr[0]),
      name: dco_decode_String(arr[1]),
      sizeBytes: dco_decode_u_64(arr[2]),
      isVideo: dco_decode_bool(arr[3]),
    );
  }

  @protected
  TorrentMetadataPayload dco_decode_torrent_metadata_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TorrentMetadataPayload(
      infoHash: dco_decode_String(arr[0]),
      files: dco_decode_list_torrent_metadata_file_payload(arr[1]),
    );
  }

  @protected
  TorrentTickPayload dco_decode_torrent_tick_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TorrentTickPayload(
      infoHash: dco_decode_String(arr[0]),
      downloadSpeedKbps: dco_decode_f_64(arr[1]),
      uploadSpeedKbps: dco_decode_f_64(arr[2]),
      peersConnected: dco_decode_usize(arr[3]),
      progressPercent: dco_decode_f_64(arr[4]),
      state: dco_decode_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  TorrentTickPayload sse_decode_box_autoadd_torrent_tick_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_torrent_tick_payload(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TorrentMetadataFilePayload>
  sse_decode_list_torrent_metadata_file_payload(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TorrentMetadataFilePayload>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_torrent_metadata_file_payload(deserializer));
    }
    return ans_;
  }

  @protected
  TorrentTickPayload? sse_decode_opt_box_autoadd_torrent_tick_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_torrent_tick_payload(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TorrentMetadataFilePayload sse_decode_torrent_metadata_file_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_usize(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_isVideo = sse_decode_bool(deserializer);
    return TorrentMetadataFilePayload(
      index: var_index,
      name: var_name,
      sizeBytes: var_sizeBytes,
      isVideo: var_isVideo,
    );
  }

  @protected
  TorrentMetadataPayload sse_decode_torrent_metadata_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_infoHash = sse_decode_String(deserializer);
    var var_files = sse_decode_list_torrent_metadata_file_payload(deserializer);
    return TorrentMetadataPayload(infoHash: var_infoHash, files: var_files);
  }

  @protected
  TorrentTickPayload sse_decode_torrent_tick_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_infoHash = sse_decode_String(deserializer);
    var var_downloadSpeedKbps = sse_decode_f_64(deserializer);
    var var_uploadSpeedKbps = sse_decode_f_64(deserializer);
    var var_peersConnected = sse_decode_usize(deserializer);
    var var_progressPercent = sse_decode_f_64(deserializer);
    var var_state = sse_decode_String(deserializer);
    return TorrentTickPayload(
      infoHash: var_infoHash,
      downloadSpeedKbps: var_downloadSpeedKbps,
      uploadSpeedKbps: var_uploadSpeedKbps,
      peersConnected: var_peersConnected,
      progressPercent: var_progressPercent,
      state: var_state,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_torrent_tick_payload(
    TorrentTickPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_torrent_tick_payload(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_torrent_metadata_file_payload(
    List<TorrentMetadataFilePayload> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_torrent_metadata_file_payload(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_torrent_tick_payload(
    TorrentTickPayload? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_torrent_tick_payload(self, serializer);
    }
  }

  @protected
  void sse_encode_torrent_metadata_file_payload(
    TorrentMetadataFilePayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.index, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_bool(self.isVideo, serializer);
  }

  @protected
  void sse_encode_torrent_metadata_payload(
    TorrentMetadataPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.infoHash, serializer);
    sse_encode_list_torrent_metadata_file_payload(self.files, serializer);
  }

  @protected
  void sse_encode_torrent_tick_payload(
    TorrentTickPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.infoHash, serializer);
    sse_encode_f_64(self.downloadSpeedKbps, serializer);
    sse_encode_f_64(self.uploadSpeedKbps, serializer);
    sse_encode_usize(self.peersConnected, serializer);
    sse_encode_f_64(self.progressPercent, serializer);
    sse_encode_String(self.state, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
