// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TorrentMetadataFilePayload {
  final BigInt index;
  final String name;
  final BigInt sizeBytes;
  final bool isVideo;

  const TorrentMetadataFilePayload({
    required this.index,
    required this.name,
    required this.sizeBytes,
    required this.isVideo,
  });

  @override
  int get hashCode =>
      index.hashCode ^ name.hashCode ^ sizeBytes.hashCode ^ isVideo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentMetadataFilePayload &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          sizeBytes == other.sizeBytes &&
          isVideo == other.isVideo;
}

class TorrentMetadataPayload {
  final String infoHash;
  final List<TorrentMetadataFilePayload> files;

  const TorrentMetadataPayload({required this.infoHash, required this.files});

  @override
  int get hashCode => infoHash.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentMetadataPayload &&
          runtimeType == other.runtimeType &&
          infoHash == other.infoHash &&
          files == other.files;
}

class TorrentTickPayload {
  final String infoHash;
  final double downloadSpeedKbps;
  final double uploadSpeedKbps;
  final BigInt peersConnected;
  final double progressPercent;
  final String state;

  const TorrentTickPayload({
    required this.infoHash,
    required this.downloadSpeedKbps,
    required this.uploadSpeedKbps,
    required this.peersConnected,
    required this.progressPercent,
    required this.state,
  });

  @override
  int get hashCode =>
      infoHash.hashCode ^
      downloadSpeedKbps.hashCode ^
      uploadSpeedKbps.hashCode ^
      peersConnected.hashCode ^
      progressPercent.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentTickPayload &&
          runtimeType == other.runtimeType &&
          infoHash == other.infoHash &&
          downloadSpeedKbps == other.downloadSpeedKbps &&
          uploadSpeedKbps == other.uploadSpeedKbps &&
          peersConnected == other.peersConnected &&
          progressPercent == other.progressPercent &&
          state == other.state;
}
